### PR TITLE
testing new branch

### PR DESCRIPTION
**Pull request by AImani2**

### CODE REVIEW

**Comment by AImani2** [comment]
Hi Professor,
Would you know what is wrong with my @GET?
Thank you!

**Comment by AImani2** [comment]
> Hi Professor, Would you know what is wrong with my @get? Thank you!

And my RijksServiceFactory?

**Comment by AImani2** [comment]
Hi Professor,
Why is my api.properties not brown like yours?
Thank you!

**Comment by andrewoid** [comment]
> Why is my api.properties not brown like yours?

As long as it's not being checked into git it's fine.

**Review by andrewoid — APPROVED** [review]

**Pull request merged**
